//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Weights = new HashSet<Weight>();
        }
    
        public int idprod { get; set; }
        public int code { get; set; }
        public Nullable<int> smlmitrach { get; set; }
        public string shmmitzrach { get; set; }
        public Nullable<double> protein { get; set; }
        public Nullable<double> total_fat { get; set; }
        public Nullable<double> food_energy { get; set; }
        public Nullable<double> carbohydrates { get; set; }
        public Nullable<double> total_dieatry_fiber { get; set; }
        public Nullable<double> calcium { get; set; }
        public Nullable<double> iron { get; set; }
        public Nullable<double> total_sugars { get; set; }
        public Nullable<double> trans_fatty_acids { get; set; }
        public Nullable<double> magnesium { get; set; }
        public Nullable<double> phosphours { get; set; }
        public Nullable<double> potassium { get; set; }
        public Nullable<double> sodium { get; set; }
        public Nullable<double> zinc { get; set; }
        public Nullable<double> cholesterol { get; set; }
        public Nullable<double> saturated_fat { get; set; }
        public Nullable<double> vitamin_a_ui { get; set; }
        public Nullable<double> vitamin_e { get; set; }
        public Nullable<double> vitamin_c { get; set; }
        public Nullable<double> vitamin_a_re { get; set; }
        public Nullable<double> vitamin_k { get; set; }
        public Nullable<double> vitamin_b6 { get; set; }
        public Nullable<double> vitamin_b12 { get; set; }
        public Nullable<double> vitamin_d { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weight> Weights { get; set; }
    }
}
